### ISSUE TITLE
Main process hangs: Closing all ReceivePorts necessary to exit main isolate

### ISSUE THREAD

**Issue by xErik** [maxim-saplin/isolate_pool_2#2] opened 2023-01-29 17:39 UTC
I did some more testing and found that (in my test case) the process hangs after `pool.stop()` has been called. 

Running `dart run test.dart` does not exit but the parent isolate is hanging. 

The issue is discussed here: 

**Solution**

The unclosed `ReceivePort`s keep the main isolate running and are blocking it from exiting. 

I tinkered the code and this fixes the 

**Test Code**

```dart
import 'package:isolate_pool_2/isolate_pool_2.dart';

// ---------------------------------------------------------
// MAIN
// ---------------------------------------------------------

void main(List<String> args) async {
  final List<Future> futures = [];
  final pool = IsolatePool(2);
  await pool.start();

  try {
    for (var i = 0; i < 10; i++) {
      final job = MyJob(i);
      futures.add(pool.scheduleJob(job));
    }

    await Future.wait(futures, eagerError: true);
  } on MyException catch (e) {
    print('CAUGHT: ${e.message}');
  } finally {
    try {
      print('STOPPING ...');
      pool.stop();
    } catch (_) {
      // ignore safety measure
    }
  }

  print('Main done!');
}

// ---------------------------------------------------------
// JOB
// ---------------------------------------------------------

class MyJob extends PooledJob {
  final int i;
  MyJob(this.i);

  @override
  job() async {
    print('JOB: $i');
    await Future.delayed(Duration(seconds: 1));

    if (i == 2) {
      throw MyException('Thrown at: $i');
    }
  }
}

// ---------------------------------------------------------
// EXCEPTION
// ---------------------------------------------------------

class MyException implements Exception {
  final String message;
  MyException(this.message);
}
```

**Comment by maxim-saplin** [comment] 2023-01-29 17:56
Closing as duplicate of #3

**Closed by maxim-saplin** 2023-01-29 17:56 UTC
